name: 'Create an event with Microsoft Graph using MSAL'
description: "Creates an event in a specified user's calendar on the next business day or on a specified date."
author: 'Anoop Tatti'
branding:
  icon: 'calendar'
  color: 'blue'
inputs:
  clientId:
    description: "The Id of the app registration."
    required: true
  clientSecret:
    description: "App registration's secret."
    required: true
  tenantId:
    description: "The Id of your Microsoft 365 tenant."
    required: true
  subject:
    description: "The subject of the event."
    required: true
  body:
    description: "The body of the event (can be HTML)."
    required: true
  userEmail:
    description: "The email address of the person for whom the event will be created."
    required: true
  start:
    description: "(Optional) The date and time when the event should start (format - yyyy-MM-ddThh:mm:ss). If not specified start time will be next day 12:00 GMT."
  end:
    description: "(Optional) The date and time when the event should end (format - yyyy-MM-ddThh:mm:ss). If not specified end time will be next day 13:00 GMT."
runs:
  using: 'node16'
  main: 'dist/index.js'
